---
- name: airflow 설치 및 db 연결
  hosts: clients
  tasks:

  - name: 파이썬 버전 지정
    set_fact:
      interpreter: /usr/bin/python3.8

  - name: 가상환경 삭제
    file:
      path: ~/airflow/venv
      state: absent

  - name: bashrc 수정
    lineinfile: 
      path: ~/.bashrc
      line: export AIRFLOW_HOME=$HOME/airflow

  - name: bashrc 적용
    shell: source ~/.bashrc

  - name: 링크 연결
    become: true
    file:
      src: /usr/bin/python3.8
      dest: /usr/bin/python3
      state: link
      force: yes
  
  - name: 링크 연결
    become: true
    file:
      src: /usr/bin/pip3
      dest: /usr/bin/pip
      state: link
      force: yes

  - name: mysql 라이브러리 설치
    become: true
    vars:
      ansible_python_interpreter: "{{ interpreter }}"
    yum:
      name: mysql-devel
      state: present

  - name: python-devel 설치
    become: true
    yum:
      name: python38-devel
      state: present
    vars:
      ansible_python_interpreter: "{{ interpreter }}"

  - name: gcc 설치
    become: true
    yum:
      name: gcc
      state: present
    vars:
      ansible_python_interpreter: "{{ interpreter }}"

  - name: pip 업그레이드
    pip:
      name: pip
      state: latest
    vars:
      ansible_python_interpreter: "{{ interpreter }}"

  - name: wheel 설치
    pip:
      name: wheel
      state: present
    vars:
      ansible_python_interpreter: "{{ interpreter }}"

  - name: mysql client 설치
    ansible.builtin.pip:
      name: mysqlclient
      state: latest
    vars:
      ansible_python_interpreter: "{{ interpreter }}"

  - name: redis 설치
    ansible.builtin.pip:
      name: redis
    vars:
      ansible_python_interpreter: "{{ interpreter }}"

  - name: 글로벌로 airflow 설치
    ansible.builtin.pip:
      name: apache-airflow[celery]
      chdir: ~/airflow
      state: latest
    vars:
      ansible_python_interpreter: "{{ interpreter }}"

  - name: config 수정 (db)
    lineinfile:
      dest: ~/airflow/airflow.cfg
      regexp: '^sql_alchemy_conn\s+'
      line: sql_alchemy_conn = mysql://{user}:{passwd}@{host}:{port}/airflow?charset=utf8

  - name: config 수정 (executor)
    lineinfile:
      dest: ~/airflow/airflow.cfg
      regexp: '^executor\s+'
      line: executor = CeleryExecutor

  - name: config 수정 (redis)
    lineinfile:
      dest: ~/airflow/airflow.cfg
      regexp: '^broker_url\s+'
      line: broker_url = redis://{user}@{host}:{port}/0

  - name: db init
    shell: ~/.local/bin/airflow db init
    args:
      chdir: ~/airflow