---
- name: python 버전 업그레이드
  hosts: clients
  become: true
  become_user: ec2-user
  tasks:
  - name: amazon-linux 설정
    shell: amazon-linux-extras enable python3.8
  - name: python3.8 설치
    yum: 
      name: python3.8
      state: present
  - name: 링크 연결
    file:
      src: /usr/bin/python3.8
      dest: /usr/bin/python3
      state: link
      force: yes
  - name: requirement 파일 전송
    copy:
      src: ../crawl/requirement.txt
      dest: ~/crawl
      force: true
  - name: 가상환경 삭제
    file:
      path: ~/crawl/venv
      state: absent
  - name: 가상환경 새로 생성
    command: python3 -m venv ~/crawl/venv
    args:
      creates: ~/crawl/venv
  - name: 가상환경 활성화
    command: source ~/crawl/venv/bin/activate
  - name: 파이썬 모듈 설치
    ansible.builtin.pip:
      requirements: ~/crawl/requirement.txt
      virtualenv: ~/crawl/venv