---
- name: python 버전 업그레이드
  hosts: clients
  become: true
  become_user: ec2-user
  tasks:
  - name: amazon-linux 설정
    shell: amazon-linux-extras enable python3.8
  - name: python3.8 설치
    yum: 
      name: python3.8
      state: present
  - name: 링크 연결
    file:
      src: /usr/bin/python3.8
      dest: /usr/bin/python3
      state: link
      force: yes